// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dump(arg1) {
  return window['go']['main']['App']['Dump'](arg1);
}

export function GetBaseline() {
  return window['go']['main']['App']['GetBaseline']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetPathFromID(arg1) {
  return window['go']['main']['App']['GetPathFromID'](arg1);
}

export function ListData(arg1) {
  return window['go']['main']['App']['ListData'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function SaveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2, arg3);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectFileNewProject() {
  return window['go']['main']['App']['SelectFileNewProject']();
}
