// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';
import {context} from '../models';

export function Dump(arg1:any):Promise<void>;

export function GetBaseline():Promise<structs.Baseline>;

export function GetFileContent(arg1:string):Promise<Record<string, structs.MedicalData>>;

export function GetPathFromID(arg1:string):Promise<string>;

export function ListData(arg1:string):Promise<Array<structs.Patient>>;

export function ListProjects():Promise<Array<structs.Project>>;

export function SaveProject(arg1:string,arg2:string):Promise<void>;

export function SelectFile(arg1:context.Context):Promise<string>;

export function SelectFileNewProject():Promise<string>;
